---
title: "Calibration"
format: html
editor: visual
---

```{r, libraries-settings}
#| message: false
#| warning: false
#| include: false
knitr::opts_chunk$set(echo = T, eval = T, message = F, warning = F)
# load libraries
library(tidyverse)
library(here)
library(ggrepel)
library(lubridate)

# Set ggplot theme
theme_set(theme_bw())
```

# Calibration

Goal: To run the code necessary to obtain a slope and offset for calibrating the Picarro

```{r}

#### User settings #############################################################
# This section contains settings for the user to edit. 
# File path to the measurments for the effective volume spreadsheet
resp_spreadsheet_fp <- "~/Downloads/Scalora_2026_01_06_Picarro_Respiration_sheet_template_iCO2-CH4_NewFormat.xlsx"

# Data about where the effective volume measurments start
start_row <- 3 # row of dataframe where measurements start - does not include header rows (e.g. row 3 in spreadsheet = 1 in dataframe)
end_row <- 28 # row of dataframe where measurements end - does not include header rows (e.g. row 23 in spreadsheet = 20 in dataframe)
exclude_sampletypes <- c("mistake") # the value of "SampleType" column for samples you want to exclude from the analyses

#### Effective Volume Calculation ##############################################
col_types_picarro <- c(rep("text", 2), #sampletype:jar number
                       rep("numeric", 16), #RoomTemperature:EffectiveIsotopicRatio
                       "date", #date last flushed
                       "date", #time last flushed
                       rep("text", 1), # comments
                       "date", # Date
                       "date", # time of start of measurements
                       rep("numeric", 8), #Mean of pre-12CO2:MeanH2O%post 
                       "text", # Remarks 
                       rep("numeric", 32), # effective volume of loop:TrueDelta permil
                       rep("guess", 12)) # regression calculations

# Read in data
std_curve_raw <- readxl::read_excel(resp_spreadsheet_fp, skip = 1,
                                    col_types = col_types_picarro,
                                    na = c("nan", "#VALUE!", "#DIV/0!", "#REF!"))

std_curve_estimation <- std_curve_raw %>%
  # Clean and filter out unnessesary columns and rows
  slice(start_row:end_row) %>%
  filter(!(SampleType %in% exclude_sampletypes)) %>% # remove rows where mistakes were made
  select(`Jar Number`,
         `Volume of sample or standard (mL of gas measured)`,
         `Room Temperature (degC)`, `RoomPressure (hPa)`,
         `Concentration of Standard Curve CO2 Gas (ppm)`,
         `Concentration of Standard Curve CH4 gas (ppm)`,
         `Atom% of Standard Curve 13CO2`,
         `Atom% of standard curve 13CH4`,
         `12CO2-PPM`,    
         `12CH4-PPM`,                                                     
         `Isotope ratio of CH4 gas`, 
         `Isotope ratio of CO2 gas`,  
         `Rvpdb`,        
         `Delta value of the CH4 gas`,  
         `Delta value of the CO2 gas`,                        
         `Date Incubation Jar was Last Flushed (Leave blank for standard curve)`,                                     
         `Time Incubation Jar was Last Flushed (Leave blank for standard curve)`,
         `Comments`,                             
         Date, `Time of start of measurement`,
         `Mean of pre 12CO2_dry concentration (PPM)`,
         `Mean of pre-12CH4 concentration (PPM)`,
         `Mean of pre delta iCH4 Raw (permil)`,
         `Mean of pre delta iCO2 Raw (permil)`,
         `Mean of post 12CO2 concentration (PPM)`,
         `Mean of post-12CH4 concentration (PPM)`,
         `Mean of post delta iCH4 Raw (permil)`,
         `Mean of post delta iCO2 Raw (permil)`,
         `Remarks`,
         `Difference in 12CO2_dry (ppm)`,
         `Difference in 12CH4 (ppm)`,
         `Effective Volume of Loop (mL)`,
         `Fractional contribution of Sample to loop 'pool' (f_a)`,
         contains("Uncalibrated"),
         contains("True")) %>%
  filter(!is.na(`Time of start of measurement`)) %>%
  # Fix time values
  mutate(MeasurementDateTime = paste0(`Date`, " ", 
                                      hour(`Time of start of measurement`), 
                                      ":", minute(`Time of start of measurement`)),
         MeasurementDateTime = ymd_hm(MeasurementDateTime),
         FlushDateTime = paste0(`Date Incubation Jar was Last Flushed (Leave blank for standard curve)`, " ", 
                                      hour(`Time Incubation Jar was Last Flushed (Leave blank for standard curve)`), 
                                      ":", minute(`Time Incubation Jar was Last Flushed (Leave blank for standard curve)`)),
         FlushDateTime = ifelse(grepl("NA", FlushDateTime), NA, ymd_hm(FlushDateTime))) %>%
  mutate(SampleNumber = row_number(),
          # true_post_concentration12co2 = `Mean of pre 12CO2_dry concentration (PPM)` + ((`12CO2-PPM`*`Volume of sample or standard (mL of gas measured)`)/(`Effective Volume of Loop (mL)` + `Volume of sample or standard (mL of gas measured)`)),
          # true_post_concentration12cH4 = `Mean of pre-12CH4 concentration (PPM)` + ((`12CH4-PPM`*`Volume of sample or standard (mL of gas measured)`)/(`Effective Volume of Loop (mL)` + `Volume of sample or standard (mL of gas measured)`)),
          # true_post_deltaCH4_value = (`Fractional contribution of Sample to loop 'pool' (f_a)`*`Delta value of the CH4 gas`)+(`Mean of pre delta iCH4 Raw (permil)`*(1-`Fractional contribution of Sample to loop 'pool' (f_a)`))
         ) %>%
   group_by(`Jar Number`) %>%
   mutate(scaled_uncal_12co2_ppm = scale(`Uncalibrated apparent 12CO2 concentration (ppm)`),
          scaled_uncal_12CH4_ppm = scale(`Uncalibrated apparent 12CH4 concentration (ppm)`),
          scaled_uncal_delta_ich4 = scale(`Uncalibrated apparent delta iCH4 value of sample (permil)`),
          outlier_12CH4 = !dplyr::between(scaled_uncal_12CH4_ppm, left = -1, right = 1),
          outlier_12co2 = !dplyr::between(scaled_uncal_12co2_ppm, left = -1, right = 1),
          outlier_delta = !dplyr::between(scaled_uncal_delta_ich4, left = -1, right = 1)) %>%
   ungroup()

#### Quality Control of Samples #####################################
# Use the plots in this section to perform quality control on your data.
# Are there any patterns in estimates related to injection time, sample volume, 
std_curve_outlier_removal <- std_curve_estimation %>%
  filter(!(SampleNumber %in% c(6))) #%>%
  #filter(`Volume of sample or standard (mL of gas measured)` > 1)

ggplot(std_curve_outlier_removal, 
       aes(y = `True amount of 12CH4 in calibration standard (uMol)`, 
           x = `Uncalibrated apparent amount of 12CH4 in sample (uMol)`)) +
  geom_point() +
  geom_point(aes(color = Date)) +
  geom_text_repel(aes(label = SampleNumber)) +
  ylab("True amount of 12CH4 in calibration standard (uMol)") + xlab("Uncalibrated apparent amount of 12CH4 in sample (uMol)") +
  theme_bw()

ggplot(std_curve_outlier_removal,
       aes(y = `True post 12CH4 (ppm)`, 
           x = `Mean of post-12CH4 concentration (PPM)`)) +
  #geom_smooth(method = "lm") +
  geom_point(aes(color = as.factor(`Volume of sample or standard (mL of gas measured)`)), alpha = 0.5) +
  geom_text_repel(aes(label = SampleNumber)) +
  geom_abline(slope = 1, intercept = 0, 
              color = "firebrick", linetype = "dashed") +
  ylab("True amount of 12CH4 in loop after sample addition (ppm)") + xlab("Uncalibrated apparent amount of 12CH4 in loop after sample addition (ppm)") +
  theme_bw()

CH412_ppmpost_std_curve <- std_curve_outlier_removal %>%
  lm(data = ., `True post 12CH4 (ppm)`~`Mean of post-12CH4 concentration (PPM)`)
summary(CH412_ppmpost_std_curve)

CH412_ppm_std_curve <- std_curve_outlier_removal %>%
  lm(data = ., `True amount of 12CH4 in calibration standard (uMol)`~`Uncalibrated apparent amount of 12CH4 in sample (uMol)`)
summary(CH412_ppm_std_curve)

# 12co2


ggplot(std_curve_outlier_removal, 
       aes(y = `True delta value in calibration standard`, 
           x = `Uncalibrated apparent delta value of sample (permil)`)) +
  geom_point(aes(color = outlier_delta)) +
  geom_text_repel(aes(label = SampleNumber)) +
  ylab("True delta of calibration standard (permil)") + 
  xlab("Uncalibrated apparent delta of sample (permil)") +
  theme_bw()

ggplot(std_curve_outlier_removal,
       aes(y = `Isotope ratio of CO2 gas`, 
           x = `Uncalibrated apparent isotope ratio of sample`)) +
  #geom_smooth(method = "lm") +
  geom_point(aes(color = as.factor(`Volume of sample or standard (mL of gas measured)`)), alpha = 0.5) +
  geom_text_repel(aes(label = SampleNumber)) +
  geom_abline(slope = 1, intercept = 0, 
              color = "firebrick", linetype = "dashed") +
  ylab("True isotope ratio of calibration standard (ppm)") + xlab("Uncalibrated apparent isotope ratio of sample") +
  theme_bw()

CO2_delta_std_curve <- std_curve_outlier_removal %>%
  lm(data = ., `True delta value in calibration standard`~`Uncalibrated apparent delta value of sample (permil)`)

summary(CO2_delta_std_curve)

CO2_isorat_std_curve <- std_curve_outlier_removal %>%
  lm(data = ., `Isotope ratio of CO2 gas`~`Uncalibrated apparent isotope ratio of sample`)

summary(CO2_isorat_std_curve)

# Isotope ratio by concentration


ggplot(data = std_curve_outlier_removal,
       aes(x = `Isotope ratio of CO2 gas`,
           y = `Concentration of Standard Curve CO2 Gas (ppm)`)) +
  geom_point() +
  geom_point(data = std_curve_outlier_removal,
             aes(x = `Uncalibrated apparent isotope ratio of sample`,
                 y = `Uncalibrated apparent total CO2 in sample (umol)`)) +
  theme_bw()

  
  
ggplot(std_curve_outlier_removal,
         aes(y = `true_post_delta_value`, 
             x = `Mean of post delta iCO2 Raw (permil)`)) +
    geom_point(aes(color = as.factor(`Volume of sample or standard (mL of gas measured)`)), alpha = 0.5) +
    geom_text_repel(aes(label = SampleNumber)) +
    geom_abline(slope = 1, intercept = 0, 
                color = "firebrick", linetype = "dashed") +
    ylab("True delta in loop after sample addition (permil)") + xlab("Uncalibrated apparent delta in loop after sample addition (permil)") +
    theme_bw()
  
CO2_deltapost_std_curve <- std_curve_outlier_removal %>%
    lm(data = ., `true_post_delta_value`~`Mean of post delta iCO2 Raw (permil)`)
summary(CO2_deltapost_std_curve)
  
  
#### Final Checks #####################################
# For the picarro calibration, extract a smaller dataframe of 19 points
set.seed(12345)
calibration_dat <- std_curve_outlier_removal %>%
    select(SampleNumber, `Jar Number`,
           `Volume of sample or standard (mL of gas measured)`,
           true_post_concentration12co2,
           `Mean of post 12CO2 concentration (PPM)`,
           true_post_concentration13co2, 
           `Mean of post-13CO2 concentration (PPM)`,
           `True delta value in calibration standard`,
           `Uncalibrated apparent delta value of sample (permil)`) %>%
    group_by(`Jar Number`, `Volume of sample or standard (mL of gas measured)`) %>%
    slice_sample(n = 1)
  
write_tsv(calibration_dat, "~/Downloads/picarro_calibration_file.tsv")

coefficients(CH412_ppmpost_std_curve)
coefficients(CO2_13_ppmpost_std_curve)
coefficients(CO2_deltapost_std_curve)

```
